Ibw\FamilyFinancesBundle\Entity\User:
  type: entity
  table: user
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 255
    password:
      type: string
      length: 255
    status:
      type: string
      length: 255
      nullable: true
    email:
      type: string
      length: 255
      nullable: true
    birthday:
      type: datetime
  oneToMany:
    userIncomes:
      targetEntity: UserIncome
      mappedBy: user
    userExpenses:
      targetEntity: UserExpense
      mappedBy: user
  manyToMany:
    userFunds:
      targetEntity: Fund
      mappedBy: users
